### ISSUE TITLE
When running this, will you be online?

### ISSUE THREAD

**Issue by lodipo308** [Jxyme/covid-19-discord-custom-status#3]
Will you be online on Discord with covid19 status when running this script also after you close Discord client?

**Comment by Jxyme** [comment]
> Will you be online on Discord with covid19 status when running this script also after you close Discord client?

No, the custom status does not control your online status. These are two separate things.

If you're not active on Discord on either your desktop or mobile device, the custom status will be invisible. As soon as you're active again, the custom status will be visible to everyone, regardless of whether your online status is set to "Online", "Idle" or "Do not Disturb".

**Comment by lodipo308** [comment]
Can you add feature that it will control online status?

**Comment by Jxyme** [comment]
Sorry, this isn't something I plan on adding as you need to use the Discord Bot API in order to get it so you appear online 24/7, which is discouraged and against Discord's ToS for user accounts. [Automated user accounts (self-bots) – Discord](https://support.discord.com/hc/en-us/articles/115002192352-Automated-user-accounts-self-bots-).

There are methods out there you can follow, but please note, there's always the possibility of being permanently banned.

**Comment by lodipo308** [comment]
When I put my discord account online using bot, the custom status from this is not displayed.

**Comment by Jxyme** [comment]
> When I put my discord account online using bot, the custom status from this is not displayed.

This is due to bots not having access to custom statuses, so you using a self-bot will prevent any custom status from being displayed.

If you're choosing to use Discord's Bot API on a user account, you'll have to implement a custom rich presence to display instead.

**Comment by romancewastaken** [comment]
> When I put my discord account online using bot, the custom status from this is not displayed.

A fix to this is using Activity for bots, since they do not have status. Use discord.js for that if you plan to use a bot
